Feature/base model
joinbox/loopback-microservice pull request #2
Opened 2018-03-20 13:18 UTC by lkappeler

2018-03-20 15:11 UTC, rcky reviewed
I don't understand why the model is created this way. It'll create a model with a totally different interface than the basic loopback models (even though idk how to do it properly). Should we use mixins?

2018-03-20 15:11 UTC, rcky commented on src/LoopbackModelBase.js
> +    constructor({ modelName, model }) {
Is there a reason to pass in an object? do we have any guidelines on this?

2018-03-20 15:11 UTC, rcky commented on src/LoopbackModelBase.js
> +        this.modelName = modelName;
We could just take the modelName of the loopback model if no other name was provided. In general I think it is a rare case you want to give our model a different name than the base model.

2018-03-20 15:11 UTC, rcky commented on src/LoopbackModelBase.js
> +        this[this.modelName] = model;
Don't see why you are assigning it to a variable property. It just makes to code less readable and might lead to collisions.

2018-03-20 17:30 UTC, eventEmitter commented on src/LoopbackModelBase.js
> +    constructor({ modelName, model }) {
i personally like it to use objects since it makes everything easy extendable

2018-04-09 20:18 UTC, linaGirl requested changes

2018-04-09 20:18 UTC, eventEmitter commented on src/LoopbackModelBase.js
> +        this[this.modelName] = model;
why are you storing this under a dynamic name and not a static one? `this.loopbackModel` would be fine, not?

2018-04-09 20:18 UTC, eventEmitter commented on src/LoopbackModelBase.js
> +     * loops recursively trought the given objects pprototypes, reurns all
typos

2018-04-09 20:18 UTC, eventEmitter commented on src/LoopbackModelBase.js
> +        const isLastPrototype = !Object.getPrototypeOf(prototype);
Originally is was thinking of checking the name of the class, which is available under `instance.constructor.name` but i didn't remember where to find this property. The current solution works fine though.

2018-04-09 20:18 UTC, eventEmitter commented on src/LoopbackModelBase.js
> +                .catch((error) => {
could be `catch(next)`

2018-04-09 20:18 UTC, eventEmitter commented on src/LoopbackModelBase.js
> +                throw LoopbackModelBase.createError(`The loopback application environment could
What does this mean? What is the solution to this problem? Be more descriptive

2018-04-26 17:28 UTC, lkappeler commented on src/LoopbackModelBase.js
> +        const isLastPrototype = !Object.getPrototypeOf(prototype);
ok

2018-05-01 14:41 UTC, linaGirl approved these changes

2018-05-02 14:37 UTC, merged

2018-05-03 07:41 UTC, rcky commented
@eventEmitter @lkappeler This Merge broke the tests! Please make sure they run! I'll add the repos to the CI today.