Fix error handler
joinbox/loopback-microservice pull request #8
Opened 2018-09-13 14:39 UTC by rcky

Fixes the error handling and docs.

2018-09-14 10:35 UTC, lkappeler approved these changes

2018-09-14 10:35 UTC, lkappeler commented on src/MicroserviceErrorHandler.js
> +                // eslint-disable-next-line no-param-reassign
should we remove this rule from our linter config?
In my opinion it often makes sense to reassign the param

2018-09-14 10:35 UTC, lkappeler commented on src/MicroserviceErrorHandler.js
> +            if (!err.serviceName) {
Is there a reason you don't user the or operator to assign this value or is it just personal preference?
`err.serviceName = err.serviceName || this.serviceName;`

2018-09-14 10:35 UTC, lkappeler commented on src/testing/mochaUtils.js
> +    watchGlobal(variableName, setter) {
nice catch :+1:

2018-09-17 07:37 UTC, linaGirl requested changes

2018-09-17 07:37 UTC, eventEmitter commented on src/MicroserviceErrorHandler.js
>              return this.handler.call(null, err, req, res, next);
why is `.call` used here?

2018-09-17 09:20 UTC, rcky commented on src/MicroserviceErrorHandler.js
> +            if (!err.serviceName) {
Did not think about that. Just wanted it to be readable.

2018-09-17 09:21 UTC, rcky commented on src/MicroserviceErrorHandler.js
>              return this.handler.call(null, err, req, res, next);
As discussed, I'll change it.

2018-09-17 09:21 UTC, rcky commented on src/MicroserviceErrorHandler.js
> +                // eslint-disable-next-line no-param-reassign
For me it might make sense to modify the parameter, especially in `reduce` functions. Apart from that I'am not fully sure. I see the sense of this rule, since it often means that we modify parameters by reference which is likely to cause side-effects. Also I've seen stuff like:

```
param = param.toJson();
```

Which is not cool!

We should have a look at this  https://eslint.org/docs/rules/no-param-reassign#props

2018-09-17 09:53 UTC, rcky commented
@eventEmitter Updated the handler call.

2018-09-17 12:21 UTC, linaGirl approved these changes

2018-09-17 12:24 UTC, merged